# Site settings
title: "misinterpret_cast"
email: jan.stephan.dd@gmail.com
description: "We'll all be mad, soon enough."
baseurl: ""
url: "https://j-stephan.github.io"
title_description: "We'll all be mad, soon enough."
#title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  j-stephan
instagram_username: 
reddit_username: 
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
